<?php if (!defined('FARI')) die(); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en" />
    <title>Authenticate</title>

    <?php stylesheetLinkTag('tripoli'); ?>
    <?php stylesheetLinkTag('style_freckle'); ?>

    <?php faviconTag(); ?>
</head>
<body>
    <div id="wrapper" class="slim">
        <div id="main">
            <div id="header">
                <h1><?php linkTo('/', 'Fireside'); ?></h1>
            </div>
            <div id="gray">
                <h2>Login below please</h2>
            </div>
            <?php foreach (flash() as $message): ?>
                <div id="flash" class="<?php echo $message['key']; ?>">
                    <h2><?php echo $message['text']; ?></h2>
                </div>
            <?php endforeach; ?>
            <?php echo $template; ?>
        </div>
    </div>
</body>
</html>